-

   name: Install docker
   hosts: server_rack_1
   become: yes



   tasks:
    - name: Install Docker
      package: 
         name: docker
         state: latest 

      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Amazon'

    - name: INSTALL DOCKER WHEN OS IS UBUNTU
      package:
         name: docker.io
         state: latest

      when: ansible_distribution == 'Ubuntu'

    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add to grp
      command: "sudo usermod -aG docker $USER"

    - name: new grp
      user:
        name: ansible_user_id
        groups: docker
        append: yes
